language: php

git:
    depth: 1

php:
    - 7.2
    - 7.3
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini || return 0;
    - composer self-update

before_script:
    - composer install --prefer-dist --no-interaction --no-suggest

script:
    - vendor/bin/phpunit
